services:
  catalogdb:
    image: postgres:16

  basketdb:
    image: postgres:16

  discountdb:
    image: postgres:16

  distributedCache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/CatalogApi/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basket.api
    build:
      context: .
      dockerfile: Services/Basket/BasketApi/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discount.grpc
    build:
      context: .
      dockerfile: Services/Discount/DiscountGrpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
      network: host
      args:
        HTTP_PROXY: ${HTTP_PROXY-}
        HTTPS_PROXY: ${HTTPS_PROXY-}
        NO_PROXY: ${NO_PROXY-}

volumes:
  postgres_catalog:
  postgres_basket:
  postgres_discount:
